# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190411_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
